name: wholesaler_user
description: ThinksMk.
publish_to: "none"
#version: 0.2.4
version: 0.2.10

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  permission_handler: ^10.2.0
  extended_image: ^6.4.1
  device_info_plus: ^8.1.0
  flutter_web_frame: ^0.0.3
  firebase_dynamic_links: ^5.0.11
#  uni_links: ^0.5.1
  share_plus: ^6.3.0
  expandable: ^5.0.1
  flutter_quill: ^6.0.0
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  cross_scroll: ^0.0.75
  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  flutter:
    sdk: flutter
  # flutter_inappwebview: ^5.1.0+3
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  flutter_rating_bar: ^4.0.0
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  iamport_flutter: ^0.10.1+3
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  kpostal: ^0.5.1
  package_info_plus: ^1.4.0
  path_provider: ^2.0.11
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_datepicker: ^19.4.56
  webviewx: ^0.2.1
  firebase_analytics: ^10.0.7
  pull_to_refresh: ^2.0.0
  launch_review: ^3.0.1
  wholesaler_partner:
    path: ../wholesaler-partner

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/shared_images_icons/
    - assets/diagraming/


  fonts:
    - family: SpoqaHanSansNeo-Medium
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.ttf
    - family: Nanum_Gothic
      fonts:
        - asset: assets/fonts/Nanum_Gothic/NanumGothic-Regular.ttf
    - family: Nanum_Myeongjo
      fonts:
        - asset: assets/fonts/Nanum_Myeongjo/NanumMyeongjo-Regular.ttf
    - family: Noto_Sans
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
    - family: Noto_Serif
      fonts:
        - asset: assets/fonts/Noto_Serif_KR/NotoSerifKR-Regular.otf

        
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/shared_images_icons/logo.png"
